fully_qualified_domain = "https://davidpeach.co.uk"
registry_name = "rhodes"
database_cluster_name = "west-elizabeth"
database_name = "strawberry"
kubernetes_cluster_name = "new-hanover"
node_pool_name = "valentine"
spaces_bucket_name = "blackwater"
